#!/bin/bash

checkArmstrong()
{
	x=$a
	sum=0
	r=0
	n=0

	while [ $x -gt 0 ]
	do
	    r=`expr $x % 10`
	    n=`expr $r \* $r \* $r`
	    sum=`expr $sum + $n`
	    x=`expr $x / 10`
	done

	if [ $sum -eq $a ]
	then
		echo "$a is an Armstrong Number."
	else
		echo "$a is not an Armstrong Number."
	fi
}

a=$1
checkArmstrong $a
